name: Docker Image Nginx

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3



    - name: Conectarse a AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Descargar los paquetes de la infraestructura de AWS en Terraform
      run: terraform init

    - name: Probar la infraestructura de AWS con Terraform
      run: terraform plan

    - name: Desplegar la Infraestructura de AWS con Terraform
      run: terraform apply -auto-approve -input=false
    
    - name: descargar llaves nginx
      run : aws s3 cp s3://terraform-ffarias-1/network/llaves-nginx.pem . 

    - name: agregar permisos a llave SSH
      run: chmod 600 llaves-nginx.pem 

    - name: Instalar Nginx en los servidores
      run: bash -x nginx.sh



