name: Docker Image Nginx

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3


    - name: Assume Role A in AWS Account A via OpenID Connect
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-session-name: account-a-session
        role-to-assume: ${{ secrets.ROLE_A_IN_ACCOUNT_A }}
        aws-region: us-east-1

    - name: Assume Role B in AWS Account B via sts:assumeRole
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-session-name: account-b-session
        role-to-assume: ${{ secrets.ROLE_B_IN_ACCOUNT_B }}
        aws-region: us-east-1
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
        role-duration-seconds: 1200

    - name: Descargar los paquetes de la infraestructura de AWS en Terraform
      run: terraform init

    - name: Probar la infraestructura de AWS con Terraform
      run: terraform plan

    - name: Desplegar la Infraestructura de AWS con Terraform
      run: terraform apply -auto-aprove -input=false

    - name: Instalar Nginx en los servidores
      run: bash nginx.sh



